preferred_backend: "onnx"
device: "cpu"
max_length: 128
tokenizer_name: "roberta-base"

prob_gate: 0.50
escalation:
  suggest: 0.50
  warn: 0.70
  enforce: 0.95



models:
  combined:
    onnx: "models/exports/model.onnx"
    torchscript: "models/exports/model_traced.pt"
    hf_dir: "models/roberta_saved"
